/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AssetGroupFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createGroup" | "realEstateAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GroupCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createGroup",
    values: [BigNumberish, BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "realEstateAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "realEstateAddress",
    data: BytesLike
  ): Result;
}

export namespace GroupCreatedEvent {
  export type InputTuple = [
    groupAddress: AddressLike,
    propertyId: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    groupAddress: string,
    propertyId: bigint,
    creator: string
  ];
  export interface OutputObject {
    groupAddress: string;
    propertyId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetGroupFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AssetGroupFactory;
  waitForDeployment(): Promise<this>;

  interface: AssetGroupFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGroup: TypedContractMethod<
    [
      _propertyId: BigNumberish,
      _targetShares: BigNumberish,
      _members: AddressLike[],
      _equityBps: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;

  realEstateAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGroup"
  ): TypedContractMethod<
    [
      _propertyId: BigNumberish,
      _targetShares: BigNumberish,
      _members: AddressLike[],
      _equityBps: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "realEstateAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "GroupCreated"
  ): TypedContractEvent<
    GroupCreatedEvent.InputTuple,
    GroupCreatedEvent.OutputTuple,
    GroupCreatedEvent.OutputObject
  >;

  filters: {
    "GroupCreated(address,uint256,address)": TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
    GroupCreated: TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
  };
}
