/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GiftEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelGift"
      | "claimGift"
      | "createGift"
      | "getGift"
      | "gifts"
      | "hasClaimed"
      | "owner"
      | "renounceOwnership"
      | "totalClaimed"
      | "totalGifts"
      | "transferOwnership"
      | "usdc"
      | "userGifts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GiftCancelled"
      | "GiftClaimed"
      | "GiftCreated"
      | "GiftExpired"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelGift",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimGift",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createGift",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "getGift", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "gifts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalGifts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userGifts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cancelGift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimGift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gifts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalGifts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userGifts", data: BytesLike): Result;
}

export namespace GiftCancelledEvent {
  export type InputTuple = [giftId: BytesLike];
  export type OutputTuple = [giftId: string];
  export interface OutputObject {
    giftId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiftClaimedEvent {
  export type InputTuple = [
    giftId: BytesLike,
    claimer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [giftId: string, claimer: string, amount: bigint];
  export interface OutputObject {
    giftId: string;
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiftCreatedEvent {
  export type InputTuple = [
    giftId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish,
    giftType: BigNumberish,
    expiryTime: BigNumberish
  ];
  export type OutputTuple = [
    giftId: string,
    creator: string,
    amount: bigint,
    giftType: bigint,
    expiryTime: bigint
  ];
  export interface OutputObject {
    giftId: string;
    creator: string;
    amount: bigint;
    giftType: bigint;
    expiryTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiftExpiredEvent {
  export type InputTuple = [giftId: BytesLike];
  export type OutputTuple = [giftId: string];
  export interface OutputObject {
    giftId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GiftEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): GiftEscrow;
  waitForDeployment(): Promise<this>;

  interface: GiftEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelGift: TypedContractMethod<[giftId: BytesLike], [void], "nonpayable">;

  claimGift: TypedContractMethod<
    [giftId: BytesLike, password: string],
    [void],
    "nonpayable"
  >;

  createGift: TypedContractMethod<
    [
      giftId: BytesLike,
      amount: BigNumberish,
      giftType: BigNumberish,
      maxClaims: BigNumberish,
      expiryTime: BigNumberish,
      passwordHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getGift: TypedContractMethod<
    [giftId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        amount: bigint;
        remainingAmount: bigint;
        giftType: bigint;
        maxClaims: bigint;
        currentClaims: bigint;
        expiryTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  gifts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        creator: string;
        amount: bigint;
        remainingAmount: bigint;
        giftType: bigint;
        maxClaims: bigint;
        currentClaims: bigint;
        expiryTime: bigint;
        passwordHash: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [giftId: BytesLike, claimer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalClaimed: TypedContractMethod<[], [bigint], "view">;

  totalGifts: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userGifts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelGift"
  ): TypedContractMethod<[giftId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimGift"
  ): TypedContractMethod<
    [giftId: BytesLike, password: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createGift"
  ): TypedContractMethod<
    [
      giftId: BytesLike,
      amount: BigNumberish,
      giftType: BigNumberish,
      maxClaims: BigNumberish,
      expiryTime: BigNumberish,
      passwordHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGift"
  ): TypedContractMethod<
    [giftId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        amount: bigint;
        remainingAmount: bigint;
        giftType: bigint;
        maxClaims: bigint;
        currentClaims: bigint;
        expiryTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gifts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        creator: string;
        amount: bigint;
        remainingAmount: bigint;
        giftType: bigint;
        maxClaims: bigint;
        currentClaims: bigint;
        expiryTime: bigint;
        passwordHash: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [giftId: BytesLike, claimer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalGifts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userGifts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "GiftCancelled"
  ): TypedContractEvent<
    GiftCancelledEvent.InputTuple,
    GiftCancelledEvent.OutputTuple,
    GiftCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GiftClaimed"
  ): TypedContractEvent<
    GiftClaimedEvent.InputTuple,
    GiftClaimedEvent.OutputTuple,
    GiftClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GiftCreated"
  ): TypedContractEvent<
    GiftCreatedEvent.InputTuple,
    GiftCreatedEvent.OutputTuple,
    GiftCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GiftExpired"
  ): TypedContractEvent<
    GiftExpiredEvent.InputTuple,
    GiftExpiredEvent.OutputTuple,
    GiftExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "GiftCancelled(bytes32)": TypedContractEvent<
      GiftCancelledEvent.InputTuple,
      GiftCancelledEvent.OutputTuple,
      GiftCancelledEvent.OutputObject
    >;
    GiftCancelled: TypedContractEvent<
      GiftCancelledEvent.InputTuple,
      GiftCancelledEvent.OutputTuple,
      GiftCancelledEvent.OutputObject
    >;

    "GiftClaimed(bytes32,address,uint256)": TypedContractEvent<
      GiftClaimedEvent.InputTuple,
      GiftClaimedEvent.OutputTuple,
      GiftClaimedEvent.OutputObject
    >;
    GiftClaimed: TypedContractEvent<
      GiftClaimedEvent.InputTuple,
      GiftClaimedEvent.OutputTuple,
      GiftClaimedEvent.OutputObject
    >;

    "GiftCreated(bytes32,address,uint256,uint8,uint256)": TypedContractEvent<
      GiftCreatedEvent.InputTuple,
      GiftCreatedEvent.OutputTuple,
      GiftCreatedEvent.OutputObject
    >;
    GiftCreated: TypedContractEvent<
      GiftCreatedEvent.InputTuple,
      GiftCreatedEvent.OutputTuple,
      GiftCreatedEvent.OutputObject
    >;

    "GiftExpired(bytes32)": TypedContractEvent<
      GiftExpiredEvent.InputTuple,
      GiftExpiredEvent.OutputTuple,
      GiftExpiredEvent.OutputObject
    >;
    GiftExpired: TypedContractEvent<
      GiftExpiredEvent.InputTuple,
      GiftExpiredEvent.OutputTuple,
      GiftExpiredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
