/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetGroupSol from "./AssetGroup.sol";
export type { assetGroupSol };
export type { AssetGroupFactory } from "./AssetGroupFactory";
export type { GiftEscrow } from "./GiftEscrow";
export type { RealEstate } from "./RealEstate";
export type { SavingsCircle } from "./SavingsCircle";
