/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RealEstateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyShare"
      | "claimYield"
      | "distributeYield"
      | "getInvestors"
      | "investments"
      | "listProperty"
      | "nextPropertyId"
      | "owner"
      | "properties"
      | "propertyInvestors"
      | "renounceOwnership"
      | "sellShare"
      | "totalYieldPerShare"
      | "transferOwnership"
      | "updatePrice"
      | "withdrawnYield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "PropertyListed"
      | "SharePurchased"
      | "ShareSold"
      | "YieldClaimed"
      | "YieldDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyShare",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listProperty",
    values: [string, string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPropertyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propertyInvestors",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellShare",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawnYield",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPropertyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawnYield",
    data: BytesLike
  ): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, owner: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyListedEvent {
  export type InputTuple = [
    id: BigNumberish,
    title: string,
    targetPrice: BigNumberish,
    totalShares: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    title: string,
    targetPrice: bigint,
    totalShares: bigint
  ];
  export interface OutputObject {
    id: bigint;
    title: string;
    targetPrice: bigint;
    totalShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharePurchasedEvent {
  export type InputTuple = [
    id: BigNumberish,
    investor: AddressLike,
    shares: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    investor: string,
    shares: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    investor: string;
    shares: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShareSoldEvent {
  export type InputTuple = [
    id: BigNumberish,
    investor: AddressLike,
    shares: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    investor: string,
    shares: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    id: bigint;
    investor: string;
    shares: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [
    id: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, investor: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributedEvent {
  export type InputTuple = [id: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [id: bigint, amount: bigint];
  export interface OutputObject {
    id: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RealEstate extends BaseContract {
  connect(runner?: ContractRunner | null): RealEstate;
  waitForDeployment(): Promise<this>;

  interface: RealEstateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShare: TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "payable"
  >;

  claimYield: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeYield: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "payable"
  >;

  getInvestors: TypedContractMethod<
    [_propertyId: BigNumberish],
    [string[]],
    "view"
  >;

  investments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { shares: bigint; amountPaid: bigint }],
    "view"
  >;

  listProperty: TypedContractMethod<
    [
      _title: string,
      _location: string,
      _description: string,
      _imageUrl: string,
      _targetPrice: BigNumberish,
      _totalShares: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  nextPropertyId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  properties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        title: string;
        location: string;
        description: string;
        imageUrl: string;
        targetPrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        pricePerShare: bigint;
        isActive: boolean;
        owner: string;
      }
    ],
    "view"
  >;

  propertyInvestors: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellShare: TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalYieldPerShare: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [_propertyId: BigNumberish, _newPricePerShare: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawnYield: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShare"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeYield"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getInvestors"
  ): TypedContractMethod<[_propertyId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "investments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { shares: bigint; amountPaid: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "listProperty"
  ): TypedContractMethod<
    [
      _title: string,
      _location: string,
      _description: string,
      _imageUrl: string,
      _targetPrice: BigNumberish,
      _totalShares: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPropertyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        title: string;
        location: string;
        description: string;
        imageUrl: string;
        targetPrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        pricePerShare: bigint;
        isActive: boolean;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propertyInvestors"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellShare"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalYieldPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _newPricePerShare: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawnYield"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyListed"
  ): TypedContractEvent<
    PropertyListedEvent.InputTuple,
    PropertyListedEvent.OutputTuple,
    PropertyListedEvent.OutputObject
  >;
  getEvent(
    key: "SharePurchased"
  ): TypedContractEvent<
    SharePurchasedEvent.InputTuple,
    SharePurchasedEvent.OutputTuple,
    SharePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ShareSold"
  ): TypedContractEvent<
    ShareSoldEvent.InputTuple,
    ShareSoldEvent.OutputTuple,
    ShareSoldEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributed"
  ): TypedContractEvent<
    YieldDistributedEvent.InputTuple,
    YieldDistributedEvent.OutputTuple,
    YieldDistributedEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropertyListed(uint256,string,uint256,uint256)": TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;
    PropertyListed: TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;

    "SharePurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      SharePurchasedEvent.InputTuple,
      SharePurchasedEvent.OutputTuple,
      SharePurchasedEvent.OutputObject
    >;
    SharePurchased: TypedContractEvent<
      SharePurchasedEvent.InputTuple,
      SharePurchasedEvent.OutputTuple,
      SharePurchasedEvent.OutputObject
    >;

    "ShareSold(uint256,address,uint256,uint256)": TypedContractEvent<
      ShareSoldEvent.InputTuple,
      ShareSoldEvent.OutputTuple,
      ShareSoldEvent.OutputObject
    >;
    ShareSold: TypedContractEvent<
      ShareSoldEvent.InputTuple,
      ShareSoldEvent.OutputTuple,
      ShareSoldEvent.OutputObject
    >;

    "YieldClaimed(uint256,address,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;

    "YieldDistributed(uint256,uint256)": TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
    YieldDistributed: TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
  };
}
