/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SavingsCircleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "circles"
      | "contribute"
      | "createCircle"
      | "getCircle"
      | "getMember"
      | "getMembers"
      | "joinCircle"
      | "lockFunds"
      | "owner"
      | "renounceOwnership"
      | "setYieldProvider"
      | "totalCircles"
      | "transferOwnership"
      | "unlockFunds"
      | "usdc"
      | "userCircles"
      | "withdraw"
      | "yieldProvider"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircleCreated"
      | "ContributionMade"
      | "FundsLocked"
      | "FundsUnlocked"
      | "MemberJoined"
      | "OwnershipTransferred"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "circles", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCircle",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCircle",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinCircle",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCircles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockFunds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userCircles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldProvider",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "circles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCircle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCircle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinCircle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCircles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCircles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "yieldProvider",
    data: BytesLike
  ): Result;
}

export namespace CircleCreatedEvent {
  export type InputTuple = [
    circleId: BytesLike,
    creator: AddressLike,
    targetAmount: BigNumberish,
    lockPeriod: BigNumberish,
    yieldPercentage: BigNumberish
  ];
  export type OutputTuple = [
    circleId: string,
    creator: string,
    targetAmount: bigint,
    lockPeriod: bigint,
    yieldPercentage: bigint
  ];
  export interface OutputObject {
    circleId: string;
    creator: string;
    targetAmount: bigint;
    lockPeriod: bigint;
    yieldPercentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [
    circleId: BytesLike,
    member: AddressLike,
    amount: BigNumberish,
    cycleNumber: BigNumberish
  ];
  export type OutputTuple = [
    circleId: string,
    member: string,
    amount: bigint,
    cycleNumber: bigint
  ];
  export interface OutputObject {
    circleId: string;
    member: string;
    amount: bigint;
    cycleNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsLockedEvent {
  export type InputTuple = [
    circleId: BytesLike,
    amount: BigNumberish,
    lockEndTime: BigNumberish
  ];
  export type OutputTuple = [
    circleId: string,
    amount: bigint,
    lockEndTime: bigint
  ];
  export interface OutputObject {
    circleId: string;
    amount: bigint;
    lockEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsUnlockedEvent {
  export type InputTuple = [
    circleId: BytesLike,
    amount: BigNumberish,
    yieldEarned: BigNumberish
  ];
  export type OutputTuple = [
    circleId: string,
    amount: bigint,
    yieldEarned: bigint
  ];
  export interface OutputObject {
    circleId: string;
    amount: bigint;
    yieldEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [circleId: BytesLike, member: AddressLike];
  export type OutputTuple = [circleId: string, member: string];
  export interface OutputObject {
    circleId: string;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    circleId: BytesLike,
    member: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [circleId: string, member: string, amount: bigint];
  export interface OutputObject {
    circleId: string;
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SavingsCircle extends BaseContract {
  connect(runner?: ContractRunner | null): SavingsCircle;
  waitForDeployment(): Promise<this>;

  interface: SavingsCircleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  circles: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        creator: string;
        targetAmount: bigint;
        lockPeriod: bigint;
        yieldPercentage: bigint;
        totalContributed: bigint;
        lockedAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        cycleNumber: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  contribute: TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCircle: TypedContractMethod<
    [
      circleId: BytesLike,
      targetAmount: BigNumberish,
      lockPeriod: BigNumberish,
      yieldPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getCircle: TypedContractMethod<
    [circleId: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        targetAmount: bigint;
        lockPeriod: bigint;
        yieldPercentage: bigint;
        totalContributed: bigint;
        lockedAmount: bigint;
        lockEndTime: bigint;
        cycleNumber: bigint;
        isActive: boolean;
        memberCount: bigint;
      }
    ],
    "view"
  >;

  getMember: TypedContractMethod<
    [circleId: BytesLike, member: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        totalContributed: bigint;
        totalWithdrawn: bigint;
        isActive: boolean;
        joinedAt: bigint;
      }
    ],
    "view"
  >;

  getMembers: TypedContractMethod<[circleId: BytesLike], [string[]], "view">;

  joinCircle: TypedContractMethod<[circleId: BytesLike], [void], "nonpayable">;

  lockFunds: TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setYieldProvider: TypedContractMethod<
    [_yieldProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  totalCircles: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockFunds: TypedContractMethod<[circleId: BytesLike], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  userCircles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdraw: TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldProvider: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "circles"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        creator: string;
        targetAmount: bigint;
        lockPeriod: bigint;
        yieldPercentage: bigint;
        totalContributed: bigint;
        lockedAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        cycleNumber: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCircle"
  ): TypedContractMethod<
    [
      circleId: BytesLike,
      targetAmount: BigNumberish,
      lockPeriod: BigNumberish,
      yieldPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCircle"
  ): TypedContractMethod<
    [circleId: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        targetAmount: bigint;
        lockPeriod: bigint;
        yieldPercentage: bigint;
        totalContributed: bigint;
        lockedAmount: bigint;
        lockEndTime: bigint;
        cycleNumber: bigint;
        isActive: boolean;
        memberCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMember"
  ): TypedContractMethod<
    [circleId: BytesLike, member: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        totalContributed: bigint;
        totalWithdrawn: bigint;
        isActive: boolean;
        joinedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMembers"
  ): TypedContractMethod<[circleId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "joinCircle"
  ): TypedContractMethod<[circleId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYieldProvider"
  ): TypedContractMethod<[_yieldProvider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCircles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockFunds"
  ): TypedContractMethod<[circleId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userCircles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [circleId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "yieldProvider"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CircleCreated"
  ): TypedContractEvent<
    CircleCreatedEvent.InputTuple,
    CircleCreatedEvent.OutputTuple,
    CircleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "FundsUnlocked"
  ): TypedContractEvent<
    FundsUnlockedEvent.InputTuple,
    FundsUnlockedEvent.OutputTuple,
    FundsUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "CircleCreated(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      CircleCreatedEvent.InputTuple,
      CircleCreatedEvent.OutputTuple,
      CircleCreatedEvent.OutputObject
    >;
    CircleCreated: TypedContractEvent<
      CircleCreatedEvent.InputTuple,
      CircleCreatedEvent.OutputTuple,
      CircleCreatedEvent.OutputObject
    >;

    "ContributionMade(bytes32,address,uint256,uint256)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "FundsLocked(bytes32,uint256,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "FundsUnlocked(bytes32,uint256,uint256)": TypedContractEvent<
      FundsUnlockedEvent.InputTuple,
      FundsUnlockedEvent.OutputTuple,
      FundsUnlockedEvent.OutputObject
    >;
    FundsUnlocked: TypedContractEvent<
      FundsUnlockedEvent.InputTuple,
      FundsUnlockedEvent.OutputTuple,
      FundsUnlockedEvent.OutputObject
    >;

    "MemberJoined(bytes32,address)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Withdrawal(bytes32,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
