/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AssetGroupInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimMyYield"
      | "contribute"
      | "contributed"
      | "equityBps"
      | "factory"
      | "isPurchased"
      | "members"
      | "propertyId"
      | "realEstateContract"
      | "targetShares"
      | "totalContributed"
      | "totalCost"
      | "totalYieldReceived"
      | "withdrawnYield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetPurchased"
      | "Contribution"
      | "YieldClaimed"
      | "YieldReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimMyYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "equityBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPurchased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propertyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "realEstateContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalContributed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalCost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalYieldReceived",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawnYield",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimMyYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "equityBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "propertyId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "realEstateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawnYield",
    data: BytesLike
  ): Result;
}

export namespace AssetPurchasedEvent {
  export type InputTuple = [propertyId: BigNumberish];
  export type OutputTuple = [propertyId: bigint];
  export interface OutputObject {
    propertyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionEvent {
  export type InputTuple = [member: AddressLike, amount: BigNumberish];
  export type OutputTuple = [member: string, amount: bigint];
  export interface OutputObject {
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [member: AddressLike, amount: BigNumberish];
  export type OutputTuple = [member: string, amount: bigint];
  export interface OutputObject {
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldReceivedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetGroup extends BaseContract {
  connect(runner?: ContractRunner | null): AssetGroup;
  waitForDeployment(): Promise<this>;

  interface: AssetGroupInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimMyYield: TypedContractMethod<[], [void], "nonpayable">;

  contribute: TypedContractMethod<[], [void], "payable">;

  contributed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  equityBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  isPurchased: TypedContractMethod<[], [boolean], "view">;

  members: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  propertyId: TypedContractMethod<[], [bigint], "view">;

  realEstateContract: TypedContractMethod<[], [string], "view">;

  targetShares: TypedContractMethod<[], [bigint], "view">;

  totalContributed: TypedContractMethod<[], [bigint], "view">;

  totalCost: TypedContractMethod<[], [bigint], "view">;

  totalYieldReceived: TypedContractMethod<[], [bigint], "view">;

  withdrawnYield: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimMyYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "contributed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "equityBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isPurchased"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "propertyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "realEstateContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "targetShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalContributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalYieldReceived"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawnYield"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AssetPurchased"
  ): TypedContractEvent<
    AssetPurchasedEvent.InputTuple,
    AssetPurchasedEvent.OutputTuple,
    AssetPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Contribution"
  ): TypedContractEvent<
    ContributionEvent.InputTuple,
    ContributionEvent.OutputTuple,
    ContributionEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;
  getEvent(
    key: "YieldReceived"
  ): TypedContractEvent<
    YieldReceivedEvent.InputTuple,
    YieldReceivedEvent.OutputTuple,
    YieldReceivedEvent.OutputObject
  >;

  filters: {
    "AssetPurchased(uint256)": TypedContractEvent<
      AssetPurchasedEvent.InputTuple,
      AssetPurchasedEvent.OutputTuple,
      AssetPurchasedEvent.OutputObject
    >;
    AssetPurchased: TypedContractEvent<
      AssetPurchasedEvent.InputTuple,
      AssetPurchasedEvent.OutputTuple,
      AssetPurchasedEvent.OutputObject
    >;

    "Contribution(address,uint256)": TypedContractEvent<
      ContributionEvent.InputTuple,
      ContributionEvent.OutputTuple,
      ContributionEvent.OutputObject
    >;
    Contribution: TypedContractEvent<
      ContributionEvent.InputTuple,
      ContributionEvent.OutputTuple,
      ContributionEvent.OutputObject
    >;

    "YieldClaimed(address,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;

    "YieldReceived(uint256)": TypedContractEvent<
      YieldReceivedEvent.InputTuple,
      YieldReceivedEvent.OutputTuple,
      YieldReceivedEvent.OutputObject
    >;
    YieldReceived: TypedContractEvent<
      YieldReceivedEvent.InputTuple,
      YieldReceivedEvent.OutputTuple,
      YieldReceivedEvent.OutputObject
    >;
  };
}
