/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRealEstateInterface extends Interface {
  getFunction(
    nameOrSignature: "buyShare" | "claimYield" | "properties"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyShare",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
}

export interface IRealEstate extends BaseContract {
  connect(runner?: ContractRunner | null): IRealEstate;
  waitForDeployment(): Promise<this>;

  interface: IRealEstateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShare: TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "payable"
  >;

  claimYield: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  properties: TypedContractMethod<
    [_propertyId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        title: string;
        location: string;
        description: string;
        imageUrl: string;
        targetPrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        pricePerShare: bigint;
        isActive: boolean;
        owner: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShare"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _shares: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [_propertyId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        id: bigint;
        title: string;
        location: string;
        description: string;
        imageUrl: string;
        targetPrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        pricePerShare: bigint;
        isActive: boolean;
        owner: string;
      }
    ],
    "view"
  >;

  filters: {};
}
