/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlashLoanSimpleReceiverBase } from "./FlashLoanSimpleReceiverBase";
export type { IFlashLoanSimpleReceiver } from "./IFlashLoanSimpleReceiver";
export type { IPool } from "./IPool";
export type { SimpleFlashLoan } from "./SimpleFlashLoan";
