/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SimpleFlashLoanInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "POOL"
      | "executeOperation"
      | "fn_RequestFlashLoan"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FlashLoanExecuted" | "FlashLoanRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "POOL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fn_RequestFlashLoan",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "POOL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fn_RequestFlashLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FlashLoanExecutedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    premium: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, premium: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    premium: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanRequestedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleFlashLoan extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleFlashLoan;
  waitForDeployment(): Promise<this>;

  interface: SimpleFlashLoanInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  POOL: TypedContractMethod<[], [string], "view">;

  executeOperation: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  fn_RequestFlashLoan: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "POOL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeOperation"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fn_RequestFlashLoan"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FlashLoanExecuted"
  ): TypedContractEvent<
    FlashLoanExecutedEvent.InputTuple,
    FlashLoanExecutedEvent.OutputTuple,
    FlashLoanExecutedEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoanRequested"
  ): TypedContractEvent<
    FlashLoanRequestedEvent.InputTuple,
    FlashLoanRequestedEvent.OutputTuple,
    FlashLoanRequestedEvent.OutputObject
  >;

  filters: {
    "FlashLoanExecuted(address,uint256,uint256)": TypedContractEvent<
      FlashLoanExecutedEvent.InputTuple,
      FlashLoanExecutedEvent.OutputTuple,
      FlashLoanExecutedEvent.OutputObject
    >;
    FlashLoanExecuted: TypedContractEvent<
      FlashLoanExecutedEvent.InputTuple,
      FlashLoanExecutedEvent.OutputTuple,
      FlashLoanExecutedEvent.OutputObject
    >;

    "FlashLoanRequested(address,uint256)": TypedContractEvent<
      FlashLoanRequestedEvent.InputTuple,
      FlashLoanRequestedEvent.OutputTuple,
      FlashLoanRequestedEvent.OutputObject
    >;
    FlashLoanRequested: TypedContractEvent<
      FlashLoanRequestedEvent.InputTuple,
      FlashLoanRequestedEvent.OutputTuple,
      FlashLoanRequestedEvent.OutputObject
    >;
  };
}
