/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AssetGroup__factory } from "./AssetGroup__factory";
export { IRealEstate__factory } from "./IRealEstate__factory";
